### ISSUE TITLE
No authentication handler is configured to handle the scheme: B2C_1_profile_edit

### ISSUE THREAD

**Issue by himadrinath** [juunas11/aspnet-core-azureadb2c-demo#1]
everything working fine only edit profile having some trouble

![b2c_1_profile_edit](https://cloud.githubusercontent.com/assets/12247490/22181239/a2d1c1bc-e0ad-11e6-9556-9ea5d85257dc.gif)

**Comment by juunas11** [comment]
Did you specify the callback path and policy id in configuration for the edit profile policy?

**Comment by himadrinath** [comment]
@juunas11 yes i did

![config](https://cloud.githubusercontent.com/assets/12247490/22181337/9634c2e4-e0b0-11e6-926d-e7239ee96743.png)

**Comment by juunas11** [comment]
Well, the repository version works for me, so I guess you should put a breakpoint in https://github.com/juunas11/aspnet-core-azureadb2c-demo/blob/master/src/AspNetCoreBtoC/AadBtoC/AzureAdB2CAppBuilderExtensions.cs#L43 and debug the app. See if the OpenIdConnect middleware is registered for that policy. Have you modified anything else in the project?

**Comment by juunas11** [comment]
Well darn. I had renamed one of the appsettings, but forgot to rename it in the example JSON file. Nice catch 👍 I committed an updated version of the example settings. Change the key "ProfileCallbackPath" to "UserProfileCallbackPath".

**Comment by himadrinath** [comment]
@juunas11  thanks a lot. let me test again and give you feedback.................

**Comment by himadrinath** [comment]
@juunas11 its working fine. thanks for your help.
